name: Deploy car.rilr20.me

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat <<EOF > .env
          DB_CONNECTION=${{ secrets.DB_CONNECTION }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Deploy
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete --exclude='.git' --exclude='.github' --exclude='.well-known'
          path: ./
          remote_path: /var/www/car.rilr20.me/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Check vendor before deploy
        run: |
          ls -la vendor
          test -f vendor/autoload.php && echo "autoload exists"
